# Generated by Django 6.1 on 2026-08-29 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hyperparameters', models.JSONField()),
                ('metrics', models.JSONField()),
                ('model_file', models.FileField(upload_to='models/')),
                ('training_history', models.JSONField()),
                ('dataset_size', models.IntegerField()),
                ('training_time', models.FloatField()),
                ('model_size', models.IntegerField(default=0)),
            ],
        ),
    ]
